### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GLareFLare22** [sqm-autorate/sqm-autorate#186]
```
BusyBox v1.36.1 (2024-05-26 02:19:39 UTC) multi-call binary.

Usage: chmod [-R] MODE[,MODE]... FILE...

MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]

        -R      Recurse
>>> Putting config file into place...
!!! Warning: An sqm-autorate config file already exists. This new config file will be created as sqm-autorate-NEW. Please review and merge any updates into your existing sqm-autorate file.
cp: can't stat '/tmp/sqm-autorate-sqm-autorate-*/config/sqm-autorate.config': No such file or directory
>>> Putting service file into place...
cp: can't stat '/tmp/sqm-autorate-sqm-autorate-*/service/sqm-autorate.service': No such file or directory
>>> Updating VERSION string to include:   [release]
sed: /usr/lib/sqm-autorate/sqm-autorate.lua: No such file or directory
>>> Cleaning up temporary files...
rm: can't remove '/tmp/sqm-autorate-install.tar.gz': No such file or directory
rm: can't remove '/tmp/sqm-autorate-sqm-autorate-*': No such file or directory
>>> Installation complete, about to start configuration.
/usr/lib/sqm-autorate/configure.sh is not found or not executable
```

Another error for me.

 Likely user error due to using snapshot build~

![image](https://github.com/sqm-autorate/sqm-autorate/assets/159732219/6a2f7f9a-0b63-4bae-869e-be467420d7e4)

**Comment by Lochnair** [comment]
That should be fixed in the latest setup script, even if you're installing another branch, use the setup script from the develop/main branch

**Comment by GLareFLare22** [comment]
> That should be fixed in the latest setup script, even if you're installing another branch, use the setup script from the develop/main branch


it had fixed the 404 error so the files are properly pulled(but it still gets hung up and displays error messages if any prior files are already there, not overwriting them, just hanging up)

 however it appears that a different issue is present / unsure if its due to using a openwrt snapshot~

**Comment by GLareFLare22** [comment]
Another issue is that after manually pulling and executing the files the instance wont load

as shown in the image below.

![image](https://github.com/sqm-autorate/sqm-autorate/assets/159732219/d7ae1766-6884-4a14-8197-1767856851a9)

**Comment by GLareFLare22** [comment]
On a fresh install, it appears to work completely fine... I'm going to assume something goes wrong when the folder is pre-made/&populated~

Removing Lines 179 - 186 in settings.lua
Removing lines 99 -103 in sqm-autorate.lua

appears to allow you to manually assign the interfaces and get it to "work" while using other instances that provide a cake(and other) qdiscs~ that have bandwidth/rate to set "speed"
